[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
meridian = "EWEYM6Ujg9j5SLxXeM2hcDY7XmWRRj6RTaJNnB8T3mn"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
