[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
meridian = "j9aDZ19LCUNscRzu4pb8xMfcB42vxKN9MKyS3ej13vR"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
