[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
meridian = "9R3jRbvh9jeQLGEggB3VXQTwj88YjUKqKM8x75SefGen"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
