/**
 * Cloudflare Pages Function: GET /api/price?symbol=NVDA&tradingDay=<unix-seconds>
 *
 * A **deterministic synthetic intraday price** for local/dev so the trading bots see realistic
 * movement instead of a single static quote — and crucially see the *same* price as each other
 * at the same moment (price is a pure function of the clock + inputs, no per-request randomness).
 *
 *   price = open × (1 + curve(symbol, day)[ progress(now, tradingDay) ])
 *
 * - open: the symbol's most-recent real close (Yahoo, same source as /api/history).
 * - progress: 0→1 over a *compressed* trading day ending at `tradingDay` (the on-chain market's
 *   settlement instant), so the price converges to the curve's end value right as the market
 *   settles. Window length = SYNTH_DAY_SECONDS (env binding; default 5400 = 90 min).
 * - curve: a real prior-day %-from-open path replayed from the committed `_intraday-curves.json`
 *   (generated by scripts/fetch-intraday-curves.mjs), chosen deterministically by (symbol, day).
 *
 * Same code serves locally (wrangler) and on devnet (deployed), so bots get identical prices on
 * both. Short edge cache (it changes intra-session). Symbol allow-listed like /api/history.
 */

import dataset from "./_intraday-curves.json";
import {
  curveIndexForDay,
  sessionProgress,
  syntheticPrice,
  type CurvePoint,
} from "./_synthetic-price";

const ALLOWED = new Set([
  "AAPL",
  "MSFT",
  "GOOGL",
  "AMZN",
  "NVDA",
  "META",
  "TSLA",
]);

const YAHOO = "https://query1.finance.yahoo.com/v8/finance/chart";
const DEFAULT_SYNTH_DAY_SECONDS = 5400; // 90-minute compressed trading day
// The price is a step function quantized to this window: all callers within the same bucket get
// the identical price, and it's also the edge-cache TTL. Small enough to feel live, large enough
// that every bot in a tick agrees.
const CACHE_SECONDS = 5;

interface DayCurve {
  day: string;
  points: CurvePoint[];
}
interface Dataset {
  pointsPerDay: number;
  curves: Record<string, DayCurve[]>;
}
const CURVES = dataset as unknown as Dataset;

interface Env {
  SYNTH_DAY_SECONDS?: string;
}

function json(body: unknown, status: number, cacheSeconds = 0): Response {
  const headers: Record<string, string> = {
    "content-type": "application/json; charset=utf-8",
  };
  if (cacheSeconds > 0)
    headers["cache-control"] = `public, max-age=${cacheSeconds}`;
  return new Response(JSON.stringify(body), { status, headers });
}

const round4 = (n: number) => Math.round(n * 1e4) / 1e4;

/** Fetch the symbol's most-recent real close as the day's open/reference. */
async function fetchOpen(symbol: string): Promise<number | null> {
  const res = await fetch(`${YAHOO}/${symbol}?range=5d&interval=1d`, {
    headers: { "user-agent": "Mozilla/5.0 (Meridian price)" },
    cf: { cacheTtl: 3600, cacheEverything: true },
  });
  if (!res.ok) return null;
  const r = (await res.json()) as {
    chart?: {
      result?: Array<{
        indicators?: { quote?: Array<{ close?: Array<number | null> }> };
      }>;
    };
  };
  const closes = r.chart?.result?.[0]?.indicators?.quote?.[0]?.close ?? [];
  for (let i = closes.length - 1; i >= 0; i--) {
    const c = closes[i];
    if (typeof c === "number" && Number.isFinite(c) && c > 0) return c;
  }
  return null;
}

/** Deterministically pick one of the symbol's day-curves by the trading day's date. */
function pickCurve(symbol: string, tradingDay: number): CurvePoint[] | null {
  const days = CURVES.curves[symbol];
  if (!days || days.length === 0) return null;
  return days[curveIndexForDay(tradingDay, days.length)].points;
}

export const onRequestGet: PagesFunction<Env> = async ({ request, env }) => {
  const url = new URL(request.url);
  const symbol = (url.searchParams.get("symbol") ?? "").toUpperCase();
  const tradingDay = Number(url.searchParams.get("tradingDay"));

  if (!ALLOWED.has(symbol)) return json({ error: "unsupported symbol" }, 400);
  if (!Number.isFinite(tradingDay) || tradingDay <= 0) {
    return json({ error: "tradingDay (unix seconds) is required" }, 400);
  }

  const synthDaySeconds =
    Number(env.SYNTH_DAY_SECONDS) > 0
      ? Number(env.SYNTH_DAY_SECONDS)
      : DEFAULT_SYNTH_DAY_SECONDS;

  const curve = pickCurve(symbol, tradingDay);
  if (!curve) return json({ error: `no curve data for ${symbol}` }, 404);

  const open = await fetchOpen(symbol);
  if (open === null)
    return json({ error: `no reference price for ${symbol}` }, 502);

  // progress 0→1 over the compressed window [tradingDay − synthDay, tradingDay], quantized to
  // CACHE_SECONDS buckets so EVERY caller in the same bucket computes the exact same value (all
  // bots agree). Without quantizing, two bots calling ms apart drift — defeating the point.
  const progress = sessionProgress(
    Date.now() / 1000,
    tradingDay,
    synthDaySeconds,
    CACHE_SECONDS
  );
  const price = syntheticPrice(open, curve, progress);
  const pctFromOpen = price / open - 1;

  return json(
    {
      symbol,
      price: round4(price),
      open: round4(open),
      pctFromOpen: round4(pctFromOpen),
      progress: round4(progress),
      synthDaySeconds,
      asOf: new Date().toISOString(),
    },
    200,
    CACHE_SECONDS
  );
};
